function myFunction(num, num1) {
}

let num = 10
let num1 = 2

myFunction(num)
console.log(myFunction(num))

// This shows a function myFunction with two arguments (num, num1)

// Num is shaded out as not mentioned within the function itself.  Unlike num1 which is being logged.Num

// num & num1 then both defined as variables equalling 10 & 2 values

// myFunction(num) is named below & therefore I think the Function has changed therefore num1 is now void & therefore should be undefined

// I got the right answer but the wrong way I feel.  Thought the function was being declared so first one was void.  But actually the second part of code doesn't have both arguments & numbers, therefore num1 is undefined 
